In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
open("/Users/olivianystrom/Desktop/Springboard/CA_Birds_of_Prey/Birds_of_Prey.csv")
df = pd.read_csv("/Users/olivianystrom/Desktop/Springboard/CA_Birds_of_Prey/Birds_of_Prey.csv")
df.drop('Unnamed: 0', axis=1, inplace=True)

In [3]:
print(df.head())
print(df['Size'].unique())

             LAST EDITED DATE        COMMON NAME           SCIENTIFIC NAME  \
0  2021-08-05 02:45:57.629774         Bald Eagle  Haliaeetus leucocephalus
1  2021-04-01 02:35:26.368505      Cooper's Hawk        Accipiter cooperii
2  2021-04-01 02:35:26.368505    Red-tailed Hawk         Buteo jamaicensis
3         2017-08-16 00:55:22   American Kestrel          Falco sparverius
4         2014-10-19 02:09:50  White-tailed Kite           Elanus leucurus

      COUNTY COUNTY CODE   LATITUDE   LONGITUDE OBSERVATION DATE  \
0  Del Norte   US-CA-015  41.754666 -124.202714       1999-01-18
1  Riverside   US-CA-065  33.531253 -117.075205       1996-10-13
2  Riverside   US-CA-065  33.462797 -115.980082       1997-08-22
3       Kern   US-CA-029  35.615712 -118.251686       1995-09-11
4   Monterey   US-CA-053  36.826080 -121.632273       1994-10-15

                     Size           Main Colors  Brown  White  Gray  Orange  \
0   goose-sized or larger          brown, white      1      1     0       0
1              crow-sized          gray, orange      0      0     1       1
2  between crow and goose  brown, white, orange      1      1     0       1
3             robin-sized   gray, orange, black      0      0     1       1
4  between crow and goose    white, gray, black      0      1     1       0

   Black
0      0
1      0
2      0
3      1
4      1
['goose-sized or larger' 'crow-sized' 'between crow and goose'
 'robin-sized' 'between robin and crow' 'between sparrow and robin']

In [4]:
#adding dummy variables for size (already did color)

df["between sparrow and robin"] = np.where(df["Size"].str.contains("between sparrow and robin"), 1, 0)
df["robin-sized"] = np.where(df["Size"].str.contains("robin-sized"), 1, 0)
df["between robin and crow"] = np.where(df["Size"].str.contains("between robin and crow"), 1, 0)
df["crow-sized"] = np.where(df["Size"].str.contains("crow-sized"), 1, 0)
df["between crow and goose"] = np.where(df["Size"].str.contains("between crow and goose"), 1, 0)
df["goose-sized or larger"] = np.where(df["Size"].str.contains("goose-sized or larger"), 1, 0)

df.head()

,LAST EDITED DATE,COMMON NAME,SCIENTIFIC NAME,COUNTY,COUNTY CODE,LATITUDE,LONGITUDE,OBSERVATION DATE,Size,Main Colors,...,White,Gray,Orange,Black,between sparrow and robin,robin-sized,between robin and crow,crow-sized,between crow and goose,goose-sized or larger
0,2021-08-05 02:45:57.629774,Bald Eagle,Haliaeetus leucocephalus,Del Norte,US-CA-015,41.754666,-124.202714,1999-01-18,goose-sized or larger,"brown, white",...,1,0,0,0,0,0,0,0,0,1
1,2021-04-01 02:35:26.368505,Cooper's Hawk,Accipiter cooperii,Riverside,US-CA-065,33.531253,-117.075205,1996-10-13,crow-sized,"gray, orange",...,0,1,1,0,0,0,0,1,0,0
2,2021-04-01 02:35:26.368505,Red-tailed Hawk,Buteo jamaicensis,Riverside,US-CA-065,33.462797,-115.980082,1997-08-22,between crow and goose,"brown, white, orange",...,1,0,1,0,0,0,0,0,1,0
3,2017-08-16 00:55:22,American Kestrel,Falco sparverius,Kern,US-CA-029,35.615712,-118.251686,1995-09-11,robin-sized,"gray, orange, black",...,0,1,1,1,0,1,0,0,0,0
4,2014-10-19 02:09:50,White-tailed Kite,Elanus leucurus,Monterey,US-CA-053,36.826080,-121.632273,1994-10-15,between crow and goose,"white, gray, black",...,1,1,0,1,0,0,0,0,1,0

In [5]:
# Note that Lat/Long coordinates can often 
#be used as-is with tree-based models like Random Forest or Gradient Boost that do not require data to be normalized. 
#Other models such as neural network models would usually require those coordinates to be normalized.

#Normalizing the Lat and Long columns

df['Lat_normalized'] = (df['LATITUDE'] - df['LATITUDE'].min()) / (df['LATITUDE'].max() - df['LATITUDE'].min())
df['Long_normalized'] = (df['LONGITUDE'] - df['LONGITUDE'].min()) / (df['LONGITUDE'].max() - df['LONGITUDE'].min())
df.drop(['Size', 'Main Colors', 'LATITUDE', 'LONGITUDE', 'LAST EDITED DATE'], axis=1, inplace=True)
print(df.columns)
print(df.iloc[:, 4:18].head())

Index(['COMMON NAME', 'SCIENTIFIC NAME', 'COUNTY', 'COUNTY CODE',
       'OBSERVATION DATE', 'Brown', 'White', 'Gray', 'Orange', 'Black',
       'between sparrow and robin', 'robin-sized', 'between robin and crow',
       'crow-sized', 'between crow and goose', 'goose-sized or larger',
       'Lat_normalized', 'Long_normalized'],
      dtype='object')
  OBSERVATION DATE  Brown  White  Gray  Orange  Black  \
0       1999-01-18      1      1     0       0      0
1       1996-10-13      0      0     1       1      0
2       1997-08-22      1      1     0       1      0
3       1995-09-11      0      0     1       1      1
4       1994-10-15      0      1     1       0      1

   between sparrow and robin  robin-sized  between robin and crow  crow-sized  \
0                          0            0                       0           0
1                          0            0                       0           1
2                          0            0                       0           0
3                          0            1                       0           0
4                          0            0                       0           0

   between crow and goose  goose-sized or larger  Lat_normalized
0                       0                      1        0.974463
1                       0                      0        0.138719
2                       1                      0        0.131762
3                       0                      0        0.350562
4                       1                      0        0.473572

In [6]:
# Split into test and train data

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 4:18], df['COMMON NAME'], test_size=0.33, random_state=42)